language: ruby
before_script:
  - sudo apt-get install libimage-exiftool-perl
before_install:
  - gem install contest regtest rim test-unit
rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - ruby-head
  - jruby-19mode
